### PR TITLE
Return a conflict error when attempting to create a service link that already exists

### LINKED ISSUE #29: Linking an environment group
hello, 

I'm trying to link an environment group but I keep getting an error while applying Terraform 

```
resource "render_web_service" "pr_web_service" {
  name              = "pr-${var.pr_number}-web"
  plan              = "starter"
  region            = "frankfurt"
  start_command     = "bundle exec puma -C config/puma.rb"
  health_check_path = "/health"

  runtime_source = {
    native_runtime = {
      auto_deploy   = false
      branch        = var.pr_branch
      build_command = "./bin/render-build.sh"
      repo_url      = "testing"
      runtime       = "ruby"
    }
  }

  maintenance_mode = {
    enabled = false
    uri     = ""
  }
}

data "render_env_group" "staging" {
  id = var.staging_env_group_id
}
resource "render_env_group_link" "pr_web_service_env_link" {
  env_group_id = data.render_env_group.staging.id
  service_ids  = [render_web_service.pr_web_service.id]
}

```

outputs:

```
Automatically approving plan
render_web_service.pr_web_service: Creating...
render_web_service.pr_web_service: Creation complete after 8s [id=srv-cs80pdogph6c73cs2kr0]
render_env_group_link.pr_web_service_env_link: Creating...
Error: Provider produced inconsistent result after apply
When applying changes to render_env_group_link.pr_web_service_env_link,
provider "provider[\"registry.terraform.io/render-oss/render\"]" produced an
unexpected new value: .service_ids: new element 1 has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
Error: Provider produced inconsistent result after apply
When applying changes to render_env_group_link.pr_web_service_env_link,
provider "provider[\"registry.terraform.io/render-oss/render\"]" produced an
unexpected new value: .service_ids: new element 2 has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### PR DESCRIPTION
**Pull request by jakemalachowski**
When adding a new service to an env group that is already linked to a service, the env group link should first be imported into Terraform state. This updates the provider to return an error when it detects an un-imported env group link to prevent an inconsistent state error after creation.

Fixes #29

### CODE REVIEW

File: internal/provider/envgroup/resource/link.go [hunk 1]
```diff
@@ -63,6 +63,24 @@ func (r *envGroupLinkResource) Create(ctx context.Context, req resource.CreateRe
...
+	}
+
+	// Attempting to create a service link for an env group that already exists and is linked to another service
+	// will result in an inconsistent state error. The user should instead import the existing env group link and
+	// update it. We check to see if the service link already exists and contains a service ID not in the plan.
+	for _, id := range existingEnvGroup.ServiceLinks {
+		if !slices.Contains(plan.ServiceIds, id.Id) {
+			resp.Diagnostics.AddError(
+				"already exists",
+				fmt.Sprintf("service link already exists for %s", existingEnvGroup.Id))
```
Comment (kitemongerer) [inline internal/provider/envgroup/resource/link.go:79]:
```suggestion
				fmt.Sprintf("service link already exists for %s please import the service link or add linked services to the terraform file", existingEnvGroup.Id))
```

Maybe give the user a little more info on how to fix the issue?

**Review by kitemongerer — APPROVED** [review]
Nice fix! It might be nice to add a little more context to the error

File: internal/provider/envgroup/resource/link.go (hunk 1 above)
Comment (jakemalachowski) [reply internal/provider/envgroup/resource/link.go]: Stuck with just suggesting importing, since that encompasses both running the import command and adding it to the Terraform file.
